### ISSUE TITLE
Программа не работает

### ISSUE THREAD

**Issue by Wrascon** [kivlab/NI-FastPaste#1]
Скачал прогу, чтобы вставлять текст в GTA V, а в итоге оказалось, что на win7x64 она и слова не может вставить в блокнот, не говоря уже об эмуляции ввода. Какие только комбинации для вставки не испробовал, но одну строчку так и не продублировал нигде. Испробовал все 4 существующих метода, ребутал комп, прога просто не работает.

**Comment by kivlab** [comment]
Если у Вас программа не вставляет текст даже в "Блокнот", Вы что-то делаете не так. Проверил только что на Win10 x64, проблем нет. На Win7 тем более не должно быть. Пробуйте разные сочетания клавиш (начните с Ctrl + 1 если не используется в системе) и различные методы вставки. Программа работает только если она запущена и свернута в трей. Если она не запущена или открыто ее окно настроек, горячие клавиши срабатывать не будут. Гарантировтаь работоспособность программы с играми, где используются нестандартные элементы управления, не могу.

**Comment by Wrascon** [comment]
Не вставлялось из-за не закрытого окна настроек... А что если я скажу, что для этого я и искал программу? Вот сижу я на этом сайте в Chrome и пробую каждый метод сюда, в блокнот и в GTA V. Что имеем в итоге:
1. В Chrome работает только 4 метод.
2. В блокноте работают все, но 2 метод стирает всё что было написано ранее, что даже Ctrl+z не откатит.
3. В GTA V работает 1 метод (как и предполагалось), но делает он это довольно долго. 140 символов за 3 секунды. Не идёт ни в какое сравнение с QuickBinder, если бы он был для GTA 5.
Как-то не по кайфу постоянно лазить в трей и методы свитчить для каждой программы.
Пойду искать другие альтернативы или напишу свои макросы Razer, скрипты Clickermann. Удачи в разработке.

**Comment by kivlab** [comment]
Всего хорошего!
